"""initial schema

Revision ID: 7f9fd9a2aee4
Revises:
Create Date: 2026-09-20 13:21:22.353289

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f9fd9a2aee4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'data_snapshot',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('instruments', sa.JSON(), nullable=False),
        sa.Column('range_start', sa.Date(), nullable=False),
        sa.Column('range_end', sa.Date(), nullable=False),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('rows', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'driver',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('kill_condition', sa.String(), nullable=False),
        sa.Column('observable', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'idea',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column(
            'source_type',
            sa.Enum(
                'paper', 'github', 'forum', 'venue-event', 'graveyard', 'internal',
                name='sourcetype',
            ),
            nullable=False,
        ),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('claimed_edge', sa.String(), nullable=True),
        sa.Column(
            'asset_class',
            sa.Enum('crypto-perp', 'crypto-spot', 'defi', 'fx', name='assetclass'),
            nullable=False,
        ),
        sa.Column('driver_id', sa.String(), nullable=True),
        sa.Column(
            'profile',
            sa.Enum('carry', 'momentum', 'mean-reversion', 'arb', 'other', name='profile'),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'candidate', 'speccing', 'implemented', 'validated', 'bench', 'live',
                'rejected', 'retired',
                name='ideastatus',
            ),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_idea_status'), ['status'], unique=False)

    op.create_table(
        'dossier',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('idea_id', sa.String(), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('rules_version', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_dossier_rules_version'), ['rules_version'], unique=False
        )

    op.create_table(
        'spec',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('idea_id', sa.String(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('data_requirements', sa.JSON(), nullable=False),
        sa.Column('rebalance', sa.String(), nullable=False),
        sa.Column('costs_model', sa.JSON(), nullable=False),
        sa.Column('code_ref', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idea_id', 'version', name='uq_spec_idea_version'),
    )
    with op.batch_alter_table('spec', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_idea_id'), ['idea_id'], unique=False)

    op.create_table(
        'stage_transition',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('idea_id', sa.String(), nullable=False),
        sa.Column(
            'from_status',
            sa.Enum(
                'candidate', 'speccing', 'implemented', 'validated', 'bench', 'live',
                'rejected', 'retired',
                name='ideastatus',
            ),
            nullable=True,
        ),
        sa.Column(
            'to_status',
            sa.Enum(
                'candidate', 'speccing', 'implemented', 'validated', 'bench', 'live',
                'rejected', 'retired',
                name='ideastatus',
            ),
            nullable=False,
        ),
        sa.Column('at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('rules_version', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('stage_transition', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_stage_transition_idea_id'), ['idea_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_stage_transition_rules_version'), ['rules_version'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_stage_transition_to_status'), ['to_status'], unique=False
        )

    op.create_table(
        'token_spend',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('stage', sa.String(), nullable=False),
        sa.Column('idea_id', sa.String(), nullable=True),
        sa.Column('agent', sa.String(), nullable=False),
        sa.Column('tokens_in', sa.Integer(), nullable=False),
        sa.Column('tokens_out', sa.Integer(), nullable=False),
        sa.Column('usd_est', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('token_spend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_spend_idea_id'), ['idea_id'], unique=False)

    op.create_table(
        'trial',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('spec_id', sa.Integer(), nullable=False),
        sa.Column('config_hash', sa.String(), nullable=False),
        sa.Column('snapshot_id', sa.String(), nullable=True),
        sa.Column('code_sha', sa.String(), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('status', sa.Enum('ok', 'error', name='trialstatus'), nullable=False),
        sa.Column('kept', sa.Boolean(), nullable=False),
        sa.Column('token_cost', sa.Integer(), nullable=True),
        sa.Column('cpu_seconds', sa.Float(), nullable=True),
        sa.Column('source', sa.Enum('qlab', 'imported', name='trialsource'), nullable=False),
        sa.CheckConstraint(
            "snapshot_id IS NOT NULL OR source = 'imported'",
            name='ck_trial_snapshot_required_unless_imported',
        ),
        sa.ForeignKeyConstraint(['snapshot_id'], ['data_snapshot.id'], ),
        sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('trial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_spec_id'), ['spec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trial_status'), ['status'], unique=False)

    op.create_table(
        'verdict',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('idea_id', sa.String(), nullable=False),
        sa.Column('spec_id', sa.Integer(), nullable=True),
        sa.Column('trial_id', sa.Integer(), nullable=True),
        sa.Column(
            'stage',
            sa.Enum(
                'preflight', 'edge', 'tail', 'profile', 'capacity', 'correlation',
                name='verdictstage',
            ),
            nullable=False,
        ),
        sa.Column('rule_id', sa.String(), nullable=False),
        sa.Column('rules_version', sa.String(), nullable=False),
        sa.Column('metric', sa.String(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('comparator', sa.String(), nullable=False),
        sa.Column('threshold', sa.Float(), nullable=False),
        sa.Column('passed', sa.Boolean(), nullable=False),
        sa.Column('data_range_start', sa.Date(), nullable=False),
        sa.Column('data_range_end', sa.Date(), nullable=False),
        sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.ForeignKeyConstraint(['spec_id'], ['spec.id'], ),
        sa.ForeignKeyConstraint(['trial_id'], ['trial.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('verdict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdict_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdict_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdict_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_verdict_rules_version'), ['rules_version'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_verdict_spec_id'), ['spec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdict_trial_id'), ['trial_id'], unique=False)

    op.create_table(
        'revival_check',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('idea_id', sa.String(), nullable=False),
        sa.Column('verdict_id', sa.Integer(), nullable=False),
        sa.Column('rejected_data_end', sa.Date(), nullable=False),
        sa.Column('eligible_at', sa.Date(), nullable=False),
        sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'outcome',
            sa.Enum('revived', 'still-dead', 'pending', name='revivaloutcome'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
        sa.ForeignKeyConstraint(['verdict_id'], ['verdict.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('revival_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revival_check_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revival_check_outcome'), ['outcome'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_revival_check_verdict_id'), ['verdict_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revival_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revival_check_verdict_id'))
        batch_op.drop_index(batch_op.f('ix_revival_check_outcome'))
        batch_op.drop_index(batch_op.f('ix_revival_check_idea_id'))

    op.drop_table('revival_check')
    with op.batch_alter_table('verdict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdict_trial_id'))
        batch_op.drop_index(batch_op.f('ix_verdict_spec_id'))
        batch_op.drop_index(batch_op.f('ix_verdict_rules_version'))
        batch_op.drop_index(batch_op.f('ix_verdict_rule_id'))
        batch_op.drop_index(batch_op.f('ix_verdict_passed'))
        batch_op.drop_index(batch_op.f('ix_verdict_idea_id'))

    op.drop_table('verdict')
    with op.batch_alter_table('trial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_status'))
        batch_op.drop_index(batch_op.f('ix_trial_spec_id'))
        batch_op.drop_index(batch_op.f('ix_trial_snapshot_id'))

    op.drop_table('trial')
    with op.batch_alter_table('token_spend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_spend_idea_id'))

    op.drop_table('token_spend')
    with op.batch_alter_table('stage_transition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_transition_to_status'))
        batch_op.drop_index(batch_op.f('ix_stage_transition_rules_version'))
        batch_op.drop_index(batch_op.f('ix_stage_transition_idea_id'))

    op.drop_table('stage_transition')
    with op.batch_alter_table('spec', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_idea_id'))

    op.drop_table('spec')
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_rules_version'))
        batch_op.drop_index(batch_op.f('ix_dossier_idea_id'))

    op.drop_table('dossier')
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_status'))
        batch_op.drop_index(batch_op.f('ix_idea_driver_id'))

    op.drop_table('idea')
    op.drop_table('driver')
    op.drop_table('data_snapshot')
    # ### end Alembic commands ###
